### PR TITLE
Some small css fixes and two new small components

### LINKED ISSUE #106: Many visual mini fixes
Spinner
Loginform
LoginButton

### PR DESCRIPTION
**Pull request by martinfjant**
Closes #106

### CODE REVIEW

File: src/containers/ItemsContainer.js [hunk 1]
```diff
@@ -14,7 +14,7 @@ class ItemsContainer extends Component {
       items: { isFetching, allItems },
     } = this.props;
 
-    return isFetching ? <p>Loading...</p> : <Items items={allItems} />;
+    return isFetching ? <Loader /> : <Items items={allItems} />;
```
Comment (AnnaRoss) [inline src/containers/ItemsContainer.js]: Looks nice :+1:

File: src/components/LineButton/LineButton.js [hunk 2]
```diff
@@ -0,0 +1,10 @@
+// @flow
```
Comment (AnnaRoss) [inline src/components/LineButton/LineButton.js]: For maintainability  purposes, is it possible to integrate an additional class into the original Button component. 
```scss
.button {
  all: unset;
  font: inherit;
  cursor: pointer;
  color: inherit;
  padding: 0.4em;
  display: flex;
  align-items: center;
  justify-content: space-around;

  &.underlined {
    padding: 1px 1px 1px 2em;
    border-bottom: 2px solid....
.....
  }
....
```
